<table cellpadding="0" cellspacing="0" border="0" width="100%" summary="">
   <tr valign="top">
	   <td width="31%" class="text">
		<h2 class="blue">Издания для бизнеса</h2>
		<i>(оптовые)</i>
		<br/><br/>
		Рекламные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=23">Коммерческие предложения</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=17">Сибирский еженедельник Реклама</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=42">Оптовый рынок Сибири</a>
			</div><br/>
		Информационные
		<div style="padding-left: 10px;">
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=26">Континент Сибирь</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=60">Эпиграф</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=10">Бизнес в Сибири</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=62">Деловой квартал</a>
			</div><br/>
		Рекламно-информационные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=14">Снабжение и сбыт</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=12">Все для офиса</a>
			</div><br/>
		Недвижимость
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=79">Коммерческая и элитная недвижимость</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=78">Справочник коммерческая недвижимость</a>
			</div><br/>
	   </td>
	<td width="3%"><div style="width:5px; height:0px;"><span></span></div></td>
	   <td width="31%" class="text">
		<h2 class="blue">Для потребителей</h2>
		<i>(розничные)</i>
		<br/><br/>
		Бесплатные рекламные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=5">Ва-Банк в Новосибирске</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=36">Метрополис</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=43">От и до</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=21">Левобережный навигатор</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=46">Соседи</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=3">В центре</a>
			</div><br/>
		Телегиды
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=53">Телесемь (a3)</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=50">ТВ неделя</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=54">Телесемь (а4)</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=55">Телесеть</a>
			</div><br/>
		Бесплатные в Академгородке
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=77">Бумеранг</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=33">Навигатор</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=56">Твой городок</a>
			</div><br/>
		Бесплатные рекламно-информационные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=35">Метро</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=39">Николаевский проспект</a>
			</div><br/>
		Глянец
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=51">Удачная покупка</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=82">Высокий класс</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=84">Дорогое удовольствие</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=83">Дом снаружи и внутри</a><br/>
				<!--a href="<?=$site->PAGES["smi_item"]["url"];?>?id=51">Удачная покупка</a><br/-->
			</div><br/>
		Газеты частных объявлений
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=11">Доска объявлений</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=22">Из рук в руки</a>
			</div><br/>
		Общественно-политические<br/>
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=4">Вечерний Новосибирск</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=41">Молодость Сибири</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=40">Новая Сибирь</a>
			</div><br/>
		Работа
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=15">Работа для вас</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=16">Работа сегодня</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=38">Профессия</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=27">Лучшие вакансии</a>
			</div><br/>
	   </td>
	<td width="3%"><div style="width:5px; height:0px;"><span></span></div></td>
	   <td width="31%" class="text">
		<h2 class="blue">Совмещенные</h2>
		<i>(оптово-розничные)</i>
		<br/><br/>
		Авто
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=58">Транссервис</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=7">Авто STOP азс</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=81">Беркут</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=8">Автошанс</a>
			</div><br/>
		Строительство и ремонт
		<div style="padding-left: 10px;">
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=47">Стройка</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=19">Ремонт</a>
			</div><br/>
		Мебель
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=32">Мебельщик Сибири</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=30">Мебель и интерьер</a>
			</div><br/>
		Недвижимость
		<div style="padding-left: 10px;">
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=45">Справочник по недвижимости</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=80">Вся недвижимость</a><br/>
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=29">Недвижимость</a>
			</div><br/>
	   </td>
   </tr>
</table>