<table cellpadding="0" cellspacing="0" border="0" width="100%" summary="">
   <tr valign="top">
	   <td width="31%" class="text">
		<h2 class="blue">Издания для бизнеса</h2>
		<i>(оптовые)</i>
		<br/><br/>
		Рекламные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=69">Оптовик Алтая</a>
			</div><br/>
		Рекламно-информационные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=71">Рекламная пауза</a><br/>
			</div><br/>
	   </td>
	<td width="3%"><div style="width:5px; height:0px;"><span></span></div></td>
	   <td width="31%" class="text">
		<h2 class="blue">Для потребителей</h2>
		<i>(розничные)</i>
		<br/><br/>
		Бесплатно распространяемые
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=76">Читай-город</a>
			</div><br/>
		Телегиды
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=75">ТВ-Пульт</a>
			</div><br/>
		Общественно-политические<br/>
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=64">Вечерний Барнаул</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=72">Свободный курс</a>
			</div><br/>
		Рекламно-информационные
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=63">Автограф</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=66">Маркер-экспресс</a><br/>
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=68">Молодежь Алтая</a>
			</div><br/>
		Газеты бесплатных объявлений
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=65">Из рук в руки</a>
			</div><br/>
		Работа
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=70">Работа сегодня</a>
			</div><br/>
	   </td>
	<td width="3%"><div style="width:5px; height:0px;"><span></span></div></td>
	   <td width="31%" class="text">
		<h2 class="blue">Совмещенные</h2>
		<i>(оптово-розничные)</i>
		<br/><br/>
		Мебель
		<div style="padding-left: 10px;">
				<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=67"> 	Мебель, благоустройство, фурнитура</a>
			</div><br/>
		Строительство и ремонт
		<div style="padding-left: 10px;">
			<a href="<?=$site->PAGES["smi_item"]["url"];?>?id=74">Стройка</a>
			</div><br/>
	   </td>
   </tr>
</table>