<h1 class="title"><span class="runrunner">Рекламу заказали — об эффекте рассказали</h1>
<br/>
<br/>
<br/>




<p>
<div style="text-align: left; padding-right: 0px;"><i>31 августа 2012</i>
</div><br/>
Было бы неэффективно, не обращалась бы к вам снова при необходимости. И вообще с вами работать хорошо: закрывающие документы для 
бухгалтерии получаем регулярно. Курьер с почты приносит. А вот работали с газетами, так от них до сих пор не можем дождаться.

<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Юлия Олеговна, директор департамента (Санкт-Петербург)</i></b>
</div>
</p>
<br/><br/><br/><br/>




<p>
<div style="text-align: left; padding-right: 0px;"><i>31 августа 2012</i>
</div><br/>
Регулярно подаем на&nbsp;&laquo;<a href="/string/item.php?id=29&order_type=0">Рен-ТВ</a>&raquo; и &laquo;<a href="/string/item.php?id=9&order_type=0">ОТС</a>&raquo;. 
Сейчас звонков стало меньше, а на работу вообще никто не выходит. В такую жару люди предпочитают отдыхать на пляже. 
<br><br>
Пытались найти работников через службу занятости, но они гонят безработных, для которых главное — получить отметку, что они не подходят, и получать пособие дальше.
<br><br>
В общем, штиль полный. Ждем, когда жара спадет.

<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Максим Борисович, директор </i></b>
</div>
</p>
<br/><br/><br/><br/>




<p>
<div style="text-align: left; padding-right: 0px;"><i>22 марта 2012</i>
</div><br/>
Подали телестроку в&nbsp;вечерний эфир на&nbsp;&laquo;<a href="/string/item.php?id=29&order_type=0">Рен-ТВ</a>&raquo;, и&nbsp;уже через сорок минут начались звонки. Я&nbsp;думал, может, кто-то шутит надо мной, но&nbsp;нет&nbsp;&mdash; смотрю, номера все разные, звонят по&nbsp;объявлению, представляются: &laquo;водитель-экспедитор&raquo;. 
<br/><br/>
Утром уже приняли человека, но&nbsp;все еще продолжают звонить... Я&nbsp;уже замучился на&nbsp;звонки отвечать. Так что, работает ваша бегущая строка.
<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Сергей Вениаминович, директор </i></b>
</div>
</p>
<br/><br/><br/><br/>




<p>
<div style="text-align: left; padding-right: 0px;"><i>20 января 2012</i>
</div><br/>

Подаем бегущую строку на&nbsp;ТВ, поскольку это эффективнее намного, чем объявления о&nbsp;вакансиях на&nbsp;&laquo;НГС&raquo; и&nbsp;
тем более&nbsp;&mdash; в&nbsp;газетах. Очень много звонков. Причем еще больше звонков, если заказываем сразу на&nbsp;два дня. Предпочитаем &laquo;<a href="http://telestroka.ru/string/item.php?id=26&order_type=0">49&nbsp;канал</a>&raquo;. Считаем, он&nbsp;эффективнее всех.
<br/><br/>
Заметили, что летом лучше подавать объявления на&nbsp;середину рабочей недели, а&nbsp;зимой&nbsp;&mdash; на&nbsp;выходные и&nbsp;праздничные дни.
<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Нина Владимировна, офис-менеджер</i></b>
</div>
</p>
<br/><br/><br/><br/>




<p>
<div style="text-align: left; padding-right: 0px;"><i>6 июня 2011</i>
</div><br/>

Подавали объявления о&nbsp;найме сотрудников и&nbsp;в&nbsp;интернете и&nbsp;в&nbsp;бегущую строку на&nbsp;телевидении. 
По&nbsp;объявлению в&nbsp;интернете звонков очень мало, а&nbsp;если и&nbsp;звонят, то&nbsp;в&nbsp;основном&nbsp;&mdash; совсем молодежь.
Так что вывод для себя сделали однозначный: бегущая строка хоть и&nbsp;дороже, но&nbsp;эффективнее. 
<br/><br/>
Обычно подаем бегущую строку на&nbsp;&laquo;<a href="http://telestroka.ru/string/item.php?id=3&order_type=0">СТС</a>&raquo; на&nbsp;выходные, так как в&nbsp;это время идет много интересных фильмов. Иногда еще заказываем менее дорогой &laquo;<a href="http://telestroka.ru/string/item.php?id=29&order_type=0">Рен ТВ</a>&raquo;.
С&nbsp;понедельника&nbsp;&mdash; шквал звонков, звонят буквально каждые две минуты.
<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Катерина, специалист по найму</i></b>
</div>
</p>
<br/><br/><br/><br/>




<p>

<div style="text-align: left; padding-right: 0px;"><i>22 марта 2007</i>
</div><br/>

Мы&nbsp;хотели, как обычно, дать объявление о&nbsp;приеме на&nbsp;работу в&nbsp;газету. Но, поскольку люди нам нужны срочно, то&nbsp;решили
попробовать телестроку.
<br/><br/>
<p>Заказ мы&nbsp;сделали в&nbsp;четверг, а&nbsp;уже на&nbsp;следующий день объявление вышло на&nbsp;&laquo;<a href="http://telestroka.ru/string/item.php?id=26&order_type=0">49&nbsp;канале</a>&raquo;. 
Звонков было много, очень много. Пока приглашаем людей на&nbsp;собеседования, и&nbsp;с&nbsp;газетной рекламной решили повременить.

<br><br/>
<div style="text-align: right; padding-right: 50px;"><b><i>Вера Воробьева, директор мебельной фабрики</i></b>
</div>
</p>

<br/><br/><br/>