<!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=16813780&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/16813780/1_0_FFFFFFFF_FFFFFFFF_0_uniques"
style="width:80px; height:15px; border:0;" alt="яндекс.ћетрика" title="яндекс.ћетрика: данные за сегодн€ (уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:16813780,type:0,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter16813780 = new Ya.Metrika({id:16813780, enableAll: true, webvisor:true});
        } catch(e) { }
    });
    
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/16813780" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->