<div class="footer">
	<p><img src="/images/design/logo.png" alt=""></p>
	<p>© 2006–2012 ООО «Телестрока»<br><a href="/notes/index.php?cat=71">Правила оказания услуг и&nbsp;подсчета стоимости</a></p>

<p>Названия и логотипы, размещенные на сайте, принадлежат их владельцам. Убедительно просим о неточностях, несоответствиях или ущемлениях прав третьих<br>
лиц незамедлительно сообщать на электронный адрес: <a href="mailto:ctc@telestroka.ru">ctc@telestroka.ru</a>. Спасибо! <strong>«Телестрока» не несет ответственности за действия недобросовестных<br>
агентств!</strong> Отзывы и предложения направляйте непосредственно руководителю: <a href="mailto:vp.baranov@yandex.ru">vp.baranov@yandex.ru</a>.</p>

<p>Спасибо, что посетили наш сайт!<br>
<? include($site->PATH_INC . '/counter.inc'); ?>
<? include($site->PATH_INC . '/counter_ya.inc'); ?>
<? include($site->PATH_INC . '/counter_ya 2.inc'); ?>
</p>
<div style="position: absolute;top: -1000px; left: -1000px">
     <a href="http://fs8.ru">Каталог интернет-магазинов Новосибирска</a>
     <a href="http://sravni-produkt.ru">Сравнение продуктов питания</a>
</div>