
<div class="sticker">
	
	<h2><a href="/feedback/">Вопросы и ответы:</a></h2>
	<br/>
	Как заказать по 20 рублей?<br/>
	Почему нельзя на ТНТ<br/>
	<span style="color: #626262">А в других городах?</span><br/>
	Заключение договоров<br/>
	Как оплатить?<br/>
	Сколько стоит слово?<br/>
	Объявление от частного лица<br/>
	<a href="/feedback/">Читать все или спросить</a>
	
	<div style="width: 0; height: 80px;"><br/></div>
	
	<img src="http://telestroka.ru/ard.jpg"><br/>
	<span style="font-size: 120%"><b>Выгодно: 2 телеканала по&nbsp;цене одного</b></span><br>

	Разместите объявление на&nbsp;&laquo;<a href="http://telestroka.ru/string/item.php?id=1">Домашнем</a>&raquo; и&nbsp;получите трансляцию на&nbsp;&laquo;<a href="http://telestroka.ru/string/item.php?id=7">ТВ3</a>&raquo; бесплатно!
	<br/>Коммерческая — принимается! (Новосибирск) 
	
	<div style="width: 0; height: 35px;"><br/></div>
	
	<a href="/string/item.php?id=3&order_type=0">
<img src="http://telestroka.ru/images/tv4cov0.jpg"></a><br/>
	<a href="http://telestroka.ru/notes/index.php?cat=713">
		<span style="font-size: 130%">
			<b>Куда хотят больше</b>
		</span>
	</a><br>
	Телеканальные предпочтения новосибирцев
	<div style="width: 0; height: 15px;"><br/></div>
	
	<div style="width: 0; height: 25px;"><br/></div>
	
	
	
	<img src="http://telestroka.ru/images/yan.jpg"><br/><br/>
		<b>
			Срочные вакансии с&nbsp;телеэкрана —&nbsp;теперь на&nbsp;Яндексе:
			<a href="http://www.yandex.ru/?add=84376&from=promocode">
			просто установите виджет телестроки!
			</a>
		</b>
	
	
</div>