<div class="widget">





	<br/><br/><br/>
	
	<!--span style="background:red; padding: 3px; "> 
	<font color="white"><i><b>Срочно в эфир!</i></font></span>
	</br><br>
		
	
	
	<span style="font-size: 110%">
	Верните компьютер 
	<a href="http://telestroka.ru/notes/index.php?cat=1755">вознаграждение — 200000 р.</a></b>
	</span>

	<img src="/images/5000.jpg">
	
	
	<br/><br/><br/-->
	
<span style="font-size: 110%"><b>Рекламу заказали — об&nbsp;эффекте <a href="/comments/">рассказали</a></b></span><br><br><br>
<img src="/images/face6.jpg">

<br><br>&laquo;Как хорошо с вами! И все документы регулярно приходят!&raquo;
<br><br><i>Юлия Олеговна, директор департамента</i>

<!--<br><br>&laquo;Звонки, конечно, есть, но... июль, жара за 30. Штиль.&raquo;
<br><br><i>Макcим Борисович, директор</i>-->


	
</div>