<h1>Заказать бегущую строку на телеканале СТС в городах:<br/></h1>
<ul class="cities">
	<li><a href="/string/item.php?id=48&order_type=0">Барнаул</a>Принимаются рекламные объявления</li>
	<li><a href="/string/item.php?id=52&order_type=0">Кузбасс</a>Одновременно в городах: Кемерово Новокузнецк</li>
	<li><a href="/string/item.php?id=3&order_type=0">Новосибирск</a>Выбирайте время трансляции: днем, вечером или сутки</li>
	<li><a href="/string/item.php?id=65&order_type=0">Омск</a>Сокращение Тр. (требуются) — бесплатно</li>
	<li class="last"><a href="/string/item.php?id=57&order_type=0">Томск</a>При заказе на 2 дня третий — бесплатно</li>
</ul>
                
<div class="accent-block electrotext">
	<? include_once($site->PATH_INC . '/work.inc'); ?>
</div>