<h1 class="title">Как доехать и пройти, в фотографиях и с пояснениями</h1>
<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/krest.jpg" alt=""/><br/>
После пивного ресторана «Tinkoff», за перекрестком 30 метров по левой стороне улицы Ленина

<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/three.jpg" alt=""/><br/>
Вход с улицы в средний подъезд в виде домика — между «Ульяновскими дверьми» и «Вестфаликой». 

<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/veska.jpg" alt=""/><br/>
Ориентир: слева от двери — вертикальная вывеска «Телестроки», сверху - «Цветущий сад»

<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/dver3.jpg" alt=""/><br/>
На втором этаже — дверь справа

<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/zvonok3.jpg" alt=""/><br/>
Пожалуйста, позвоните.

<div style="width: 0; height: 45px;"><br/></div>
<img src="/images/ofis.jpg" alt=""/><br/>
Рабочее место специалиста в пункте приема объявлений «Телестроки»
<br/><br/>
<b>Каждый будний день, с 9.30 до 17.00</b>
